# Generated by Django 5.1.6 on 2025-03-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
