# Generated by Django 5.1.6 on 2025-03-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialgoal',
            options={'ordering': ['target_date']},
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='category',
            field=models.CharField(choices=[('travel', 'Подорожі'), ('housing', 'Житло'), ('education', 'Освіта'), ('retirement', 'Пенсія'), ('emergency', 'Резервний фонд'), ('other', 'Інше')], default='other', max_length=15),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='goal_type',
            field=models.CharField(choices=[('saving', 'Накопичення'), ('spending', 'Зменшення витрат'), ('investment', 'Інвестування')], max_length=12),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.financialgoal')),
            ],
        ),
    ]
