# Generated by Django 5.1.6 on 2025-03-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_financialgoal_options_financialgoal_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialgoal',
            name='notification_date',
        ),
    ]
