# Generated by Django 5.1.6 on 2025-03-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Їжа'), ('transport', 'Транспорт'), ('housing', 'Житло'), ('entertainment', 'Розваги'), ('clothing', 'Одяг'), ('health', "Здоров'я"), ('insurance', 'Страхування'), ('utilities', 'Комунальні послуги'), ('emergency', 'Резервний фонд'), ('goals', 'Цілі'), ('other', 'Інше')], max_length=20),
        ),
    ]
