# Generated by Django 5.1.6 on 2025-03-11 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_type', models.CharField(choices=[('salary', 'Заробітна плата'), ('investment', 'Інвестиції'), ('freelance', 'Фріланс'), ('other', 'Інше')], default='other', max_length=20)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('recurrence', models.CharField(choices=[('one-time', 'Разовий'), ('monthly', 'Щомісячний'), ('weekly', 'Щотижневий')], default='one-time', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
